### ISSUE TITLE
RMC unwinding-assertions should be on by default

### ISSUE THREAD

**Issue by nchong-at-aws** [model-checking/rmc#156]
RMC should use `--unwinding-assertions` by default and have an option to disable the checks. The tool should suggest increasing loop bounds or disabling unwinding assertions if these assertions fail.

**Comment by adpaco-aws** [comment]
@danielsn suggested having a few flags on by default (`--unwinding-assertions` being one of them), and provide a new flag (e.g., `--no-safe-options`) to disable them manually.
