### ISSUE TITLE
Unimplemented intrinsics required to codegen Firecracker vmm

### ISSUE THREAD

**Issue by nchong-at-aws** [model-checking/rmc#158]
Not implemented intrinsics:
- atomic_xchg
- atomic_xchg_acq
- atomic_xchg_acqrel
- atomic_xchg_rel
- atomic_xchg_relaxed
- try

**Comment by adpaco-aws** [comment]
We have `atomic_cxchg*` implemented so it should be easy to support these atomic intrinsics. `try` seems a little harder though.
