### ISSUE TITLE
Allow entry-point for `rmc` other than `main`

### ISSUE THREAD

**Issue by vecchiot-aws** [model-checking/rmc#169]
CBMC allows us to specify an entry-point other than `main`, which would be useful for analyzing a library crate, for example. However, if we try to do this, we get an error from `rmc-rustc`:

File (test.rs):
```
fn main2() {
    assert!(true);
}
```

Command: `rmc --verbose test.rs -- --function main2`

Error:
```
[RMC] stage: compile (FAIL)
[RMC] cmd: rmc-rustc -Z codegen-backend=gotoc --cfg=rmc -o test.json test.rs
error[E0601]: `main` function not found in crate `test`
 --> test.rs:1:1
  |
1 | / fn main2() {
2 | |     assert!(true);
3 | | }
  | |_^ consider adding a `main` function to `test.rs`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0601`.
```

**Comment by vecchiot-aws** [comment]
Note: I believe this only applies to `rmc`, not `cargo-rmc`. If we go to `src/test/cargo-rmc/simple-lib` and run `cargo-rmc --function test_sum .`, verification works properly.

**Comment by celinval** [comment]
I believe the problem here is that we are trying to compile the crate as an executable. We should be able to combine `--function` with  `--crate-type=lib` construction.
