### ISSUE TITLE
Proposal for how to stub stdlib

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/rmc#252]

**Comment by adpaco-aws** [comment]
My first proposal is to use [conditional compilation](http://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/book/first-edition/conditional-compilation.html). At present, we are passing `--cfg=rmc` whenever we compile or run RMC and I would expect this to work well for some parts of the standard library.

For example, in `library/alloc/src/lib.rs` we can see the vector module declaration:
```rust
pub mod vec;
```
Assuming we have rewritten the vector implementation in a `rmc_vec` module, I would expect the following change in `lib.rs` to use our version and not the standard one:

```rust
#[cfg(not(rmc))]
pub mod vec;
#[cfg(rmc)]
pub mod rmc_vec;
```
Not compiling the original `vec` module is necessary because otherwise we would get conflict definitions. This has several advantages: It's quite granular (mod-level replacement), it's a small change in the compiler's code, and doesn't need a special case in RMC to work.

**Comment by adpaco-aws** [comment]
@chinmaydd has been experimenting with this and, even though he is not using the conditional compilation flags in the standard library code (i.e., `library/alloc/src/lib.rs`) as in the original proposal (packages that depend on the vector library make it quite difficult), he has a working version where he defines the following in the testing prelude:

```rust
// src/test/rmc-prelude.rs

mod stub;

#[cfg(abs_type = "std")]
use std::vec::Vec;
#[cfg(abs_type = "rmc")]
use stub::rmc_vec::Vec;
```

This allows one to pass the `--abs_type="rmc"` flag to use the vector implementation from the stub module, at least for running tests. We assume that a similar solution can be applied to run RMC on any example, and the user can switch between any of the two vector versions by using flags.

Note that this compiles both the standard and stubbed implementations when compiling RMC. Then depending on the flags we will generate a GotoC program by pulling in one of these implementations. In regards to granularity, we need to implement all functions in the vector module but the idea is to have a default implementation with `assert(false)` as we usually do for anything that is not implemented. Finally, we can define a collection of stubbed implementations within an external crate so that we do not interfere with the Rust compiler code.

**Comment by nchong-at-aws** [comment]
Thanks @adpaco-aws  and @chinmaydd . This sounds sensible to me. If there are multiple abstractions then this will also work so that's good, although I expect that to be a more advanced feature.

Does this stubbing apply to /any/ use of the vector implementation or only the vectors used by the proof harness? For example, what if the proof harness has a dependency on a crate that itself uses vector or if the example uses a data-structure which internally uses vectors. Is the replacement good for all of those cases too? Otherwise, there is a potential problem where a stubbed vector gets used where a "real" vector is expected. Since they are method-wise compatible I think we'd only be in difficulty if there is some serious introspection, but nonetheless, an interesting case.

**Comment by adpaco-aws** [comment]
Just had a discussion with @chinmaydd about that.

We believe there are only two ways for stubbing such usages:
 1. Use hooks.
 2. Replace the std-lib implementation.
Note that we have tried (2) by using conditional compilation and we had difficulties when compiling RMC since other modules (e.g., `BinaryHeap`) depend on the standard `Vec` implementation.

Another option would be to replace them in the GotoC program, but this would be quite complicated and would still require some sort of hooking anyway (i.e., to generate the functions to be replace in the goto program). We are going to ask on Zulip in case we have missed some alternative.

**Comment by chinmaydd** [comment]
Agree with the ideas. I think the concern of external crates using the stdlib implementation over the stub is a valid one. Although both are methodwise compatible, we dont model some things like allocator-behavior which might cause unsound behavior.

**Comment by adpaco-aws** [comment]
This proposal seem to work fine for the initial experiments on stubbing stdlib. Given that this depends much on other stuff (e.g., interface with the compiler) that is surely going to change in the next few months, we are closing this issue and open a new one when needed.
