### ISSUE TITLE
Codegen failure: Unsupported intrinisic simd_shuffle8

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/rmc#309]
One version of RMC has shown this panic while codegen'ing the rand crate (#111):
```
thread 'rustc' panicked at 'not implemented: unsupported intrinsic: simd_shuffle8
```

With `main-153-2021-07-02` I got a different failure (#308) but I think we will eventually hit this one too.

**Comment by tedinski** [comment]
Update:

It looks like while CBMC has `shuffle_vector_exprt`, this is not a node type that the CBMC back-end understands. It appears the C front-end constructs this and lowers it immediately to what it translates to. We wouldn't be able to emit this in our symbol table.

I'm going to replicate it's lowering on the RMC side to resolve this issue. It's not clean having this "duplication", but I think it'll be a useful exercise for me to figure out how to do, and I'll open a new issue to track improving this implementation if/when cbmc's `shuffle_vector` becomes usable.
