### ISSUE TITLE
Pre-process extracted examples before running RMC on them.

### ISSUE THREAD

**Issue by bdalrhm** [model-checking/rmc#324]
Before we run RMC on the extracted examples from the Rust books, we need to do the following pre-processing steps:

- [x] Extract compiler annotations in code blocks and translate them to appropriate RMC flags.
- [x] #407
- [x] #408

**Comment by adpaco-aws** [comment]
Closing this issue because the tools to do this are already there.

We only need to study the examples and include assertions on a case-by-case basis. Opened #517 for that.
