### ISSUE TITLE
`_fail` tests should fail if compilation fails

### ISSUE THREAD

**Issue by vecchiot-aws** [model-checking/rmc#338]
The test at `src/test/cbmc/DynTrait/main_fail.rs` uses `_VERIFIER_expect_fail` instead of `__VERIFIER_expect_fail`, causing it to have a rust compile error. 

I expect it went by unnoticed because we (accidentally?) left in the `_fail` suffix, when really it shouldn't fail, and we don't distinguish between compilation failure and verification failure.

**Comment by avanhatt** [comment]
Oh oh, we should totally distinguish between compilation and verification failures (I thought we did, unless a test was `_ignore` or `_fixme`).

**Comment by avanhatt** [comment]
Fixing this actual test in #342, but let's use this issue to track failing for `_fail` compilation errors?

**Comment by bdalrhm** [comment]
You're both right. We don't currently check for the kind of errors we get from tests. I happen to need this feature for the dashboard as well. So, I will make it a priority.
