### ISSUE TITLE
Generated symbols for statics are sometimes not labelled correctly.

### ISSUE THREAD

**Issue by vecchiot-aws** [model-checking/rmc#369]
Two cases here:

1) `SizeAndAlignOfDst/main_fail.rs`

Running `rmc --keep-temps main_fail.rs` and then opening `main_fail.json`, we find the following symbol:
```
    "_ZN3std9panicking11panic_count18GLOBAL_PANIC_COUNT17hbb0e4a14d9617703E": {
      "baseName": "_ZN3std9panicking11panic_count18GLOBAL_PANIC_COUNT17hbb0e4a14d9617703E",
      "isAuxiliary": false,
      "isExported": false,
      "isExtern": false,
      "isFileLocal": false,
      "isInput": false,
      "isLvalue": true,
      "isMacro": false,
      "isOutput": false,
      "isParameter": false,
      "isProperty": false,
      "isStateVar": true,
      "isStaticLifetime": false,
      "isThreadLocal": true,
      "isType": false,
      "isVolatile": false,
      "isWeak": false,
      ...
```

which comes from the Rust library: [Rust Internal Docs](https://stdrs.dev/nightly/x86_64-pc-windows-gnu/std/panicking/panic_count/static.GLOBAL_PANIC_COUNT.html)

I believe this should have, instead:
```
      "isStaticLifetime": true,
      "isThreadLocal": false,
```

2) The following code (`main.rs`):

```
static A: u32 = 1;
static mut B: u32 = 2;

extern "C" {
    static C: u32;
    static mut D: u32;
}

fn main() {
    static E: u32 = 5;
    static mut F: u32 = 6;

    unsafe {
        assert!(A == 1);
        assert!(B == 2);
        assert!(C == 3);
        assert!(D == 4);
        assert!(E == 5);
        assert!(F == 6);
    }
}
```

Running `rmc --keep-temps main.rs` and then opening `main.json`, we find the a symbol for each static. All of the fields are the same as above except `"baseName"`, and possibly `"isStaticLifetime"` and `"isThreadLocal"`.

The ones with `isStaticLifetime` as `true` and `isThreadLocal` as `false` are `A`, `B`, `E`,  and `F`. 
The ones with `isStaticLifetime` as `false` and `isThreadLocal` as `true` are `C` and `D`.

---

It looks from the above examples that statics within `extern` blocks and that are in the Rust library are given incorrect tags.

Note that if we don't include the assertions in the second example, then `A`, `B`, `E`, and `F` symbols are all still generated, but `C` and `D` are not.

**Comment by danielsn** [comment]
It looks like we're generating the extern statics as needed, not as part of an initial pass.  I wonder if there is a flag we can look at when we generate those variables.
