### ISSUE TITLE
2021 week 35: rebase off upstream (merge)

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/rmc#460]

**Comment by celinval** [comment]
Merging against upstream. Upstream head is: [Auto merge of #88161 - michaelwoerister:fix-whole-archive-no-bundle, …](https://github.com/rust-lang/rust/commit/73641cd23ba470c6b4dcd72b8d5f62d27c735254)

Merge conflict in `src/bootstrap/builder.rs`
