### ISSUE TITLE
Confused about Reported Errors

### ISSUE THREAD

**Issue by DavePearce** [model-checking/rmc#506]
Hey all,

So, I've been trying out RMC with a simple program (see below) and getting a bit confused about all the errors its reporting.  For example:

```
[indexof.pointer_arithmetic.1] line 3 pointer arithmetic: pointer NULL in items.data + var_18: SUCCESS 
```

This seems a bit odd to me since its implying we have a `NULL` pointer which isn't possible, right?  

I feel like I missed something!

Cheers,

```Rust
fn indexof(items: &[u32], item: u32) -> usize {
  for i in 0..items.len() {
    if items[i] == item {
        return i;
    }
  }
  //
  return usize::MAX;
}

fn __nondet() -> [u32;3] {
  unimplemented!()
}
fn __VERIFIER_assume(cond: bool) {
  unimplemented!()
}

#[cfg(rmc)]
#[no_mangle]
pub fn main() {
    let xs = __nondet();
    //
    assert!(indexof(&xs,0) == 0);
} 
```

**Comment by zhassan-aws** [comment]
Thanks for trying out RMC! The reporting is indeed a bit confusing. The relevant piece of information is what appears at the end of the line: `SUCCESS` indicates the check was proven (no issue), and `FAILURE` indicates that the check in question failed (bug). What precedes the `SUCCESS/FAILURE` is the type of issue that is being checked. So, in your example, the check was proven indicating that there is no bug.

**Comment by DavePearce** [comment]
Hey @zhassan-aws,

Ok, thanks --- that's helping.  It says verification failed, but if I scroll up through the messages I see that its complaining about my `assert` which, in fact, doesn't hold any more :)
