### ISSUE TITLE
Spurious failures with cargo

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/rmc#550]
On a single-source-file cargo package, I'm observing failures when running RMC via cargo that do not appear when running RMC directly on the source file.

Steps to reproduce:
1. `cargo new --lib foo`
2. `cd foo`
3. Put the following in `src/lib.rs`:
```rust
pub fn main() {

    let a = [0];
    let mut b = [1];

    b[..].copy_from_slice(&a[..]);
    assert!(b[0] == 0);
}
```
4. Run RMC via `cargo` using:
```
RUST_BACKTRACE=1 RUSTFLAGS="-Z trim-diagnostic-paths=no -Z codegen-backend=gotoc --cfg=rmc" RUSTC=rmc-rustc cargo build --target x86_64-unknown-linux-gnu
```
5. `cd target/x86_64-unknown-linux-gnu/debug/deps`
6. `symtab2gb foo*.json --out foo.out`
7. `goto-cc --function main foo.out -o a.out`
8. `goto-instrument --drop-unused-functions a.out b.out`
9. `cbmc b.out`

CBMC produces the following:
```
** Results:
[precondition_instance.1] memcpy src/dst overlap: SUCCESS
[precondition_instance.2] memcpy source region readable: FAILURE
[precondition_instance.3] memcpy destination region writeable: FAILURE
/home/ubuntu/examples/new-iss/foo/src/lib.rs function main
[main.assertion.1] line 7 assertion failed: b[0] == 0: SUCCESS

/home/ubuntu/tools/rmc/library/core/src/slice/mod.rs function core::slice::<impl [T]>::copy_from_slice
[core::slice::<impl [T]>::copy_from_slice.assertion.1] line 3055 a panicking function core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail is invoked: SUCCESS

** 2 of 5 failed (2 iterations)
VERIFICATION FAILED
```

with RMC version: `7635cfebfa5`

If I instead run RMC directly on `lib.rs`, I don't see any failures:
```
$ rmc src/lib.rs
...
** 0 of 39 failed (1 iterations)
VERIFICATION SUCCESSFUL
```
Interestingly, adding `--reachability-slice` to the `goto-instrument` arguments in step 8 above makes the failures disappear (possibly related to https://github.com/diffblue/cbmc/issues/6394).

**Comment by celinval** [comment]
It looks like you are missing the `rmc_lib.c` file in the `goto-cc` command. If you add that, the failures disappear. Weird enough, that file is empty. @danielsn might have more background on why this is needed.

BTW, you should also be able to verify using `cargo rmc`.

**Comment by zhassan-aws** [comment]
Closing this since it's an issue with the command sequence used. I verified that this issue does not occur with `cargo rmc`.
