### ISSUE TITLE
Failed to run custom build command error with cargo

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/rmc#613]
I'm seeing an error whenever I run `cargo rmc` or `RUSTC=rmc-rustc cargo build`:
```
error: failed to run custom build command for `libc v0.2.106`

Caused by:
  could not execute process `/home/ubuntu/examples/debug/iss533/bar/target/debug/build/libc-8de24690c68dbcab/build-script-build` (never executed)

Caused by:
  No such file or directory (os error 2)
```
Steps to reproduce:
1. `cargo new --lib foo`
2. Add `rand = "0.8.4"` to the `Cargo.toml` dependencies
3. Run `RUST_BACKTRACE=1 RUSTFLAGS="-Z trim-diagnostic-paths=no -Z codegen-backend=gotoc --cfg=rmc" RUSTC=rmc-rustc cargo build --target x86_64-unknown-linux-gnu -j1`

with RMC version: `a431229efd2`

**Comment by celinval** [comment]
Cargo build calls rustc with many different options and it probably ignores the RUSTC_FLAGS when compiling the build.rs. (https://doc.rust-lang.org/cargo/reference/build-scripts.html)

I think once I moved the flags to be inside rmc-rustc script, we are trying to compile the build.rs with rmc enabled. I'll have to change cargo rmc implementation to use rmc-rustc to get the configuration but it cannot call it directly. I think the long term solution is to stop using cargo build.

**Comment by celinval** [comment]
To work around this issue, please follow what the [codegen-firecracker.sh](https://github.com/model-checking/rmc/blob/main/scripts/codegen-firecracker.sh#L30) script.
Replace:
```bash
RUSTC=rmc-rustc cargo build
```
By:
```bash
RUSTC=$(rmc-rustc --rmc-path) RUSTFLAGS=$(rmc-rustc --rmc-flags) cargo build  --target x86_64-unknown-linux-gnu
```

I'm going to submit a fix to `cargo rmc` so it will use a similar logic. However, to fully fix this issue we still need to add support to `--target`. I won't be able to create a test case until then.
