### ISSUE TITLE
An API for creating a non-deterministic slice

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/rmc#614]
Requested feature: Creating a non-deterministic slice (with non-deterministic content as well as a non-deterministic length) currently requires multiple steps. For example, the following code creates a non-deterministic slice of `u8` with a maximum length of 10:
```rust
let arr: [u8; 10] = rmc::nondet();
let slice_len: usize = rmc::nondet();
rmc::assume(slice_len <= 10);
&arr[..slice_len]
```
It would be useful to wrap this in some API to simplify creating non-deterministic slices.
Use case: To test functions that take a slice.
Link to relevant documentation (Rust reference, Nomicon, RFC):
Is this a breaking change?

**Comment by zhassan-aws** [comment]
This is one possible API for creating non-deterministic slices:
```rust
pub struct NdSlice<T, const MAX_SLICE_LENGTH: usize> {
    arr: [T; MAX_SLICE_LENGTH],
    slice_len: usize,
}

impl<T, const MAX_SLICE_LENGTH: usize> NdSlice<T, MAX_SLICE_LENGTH> {
    pub fn new() -> Self {
        let arr: [T; MAX_SLICE_LENGTH] = rmc::nondet();
        let slice_len: usize = rmc::nondet();
        rmc::assume(slice_len <= MAX_SLICE_LENGTH);
        Self { arr, slice_len }
    }

    pub fn get_slice(&self) -> &[T] {
        &self.arr[..self.slice_len]
    }

    pub fn get_slice_mut(&mut self) -> &mut [T] {
        &mut self.arr[..self.slice_len]
    }
}
```

**Comment by celinval** [comment]
It looks good to me. Can you expand the name a little bit? `NonDetSlice` for example.

Are you adding this to the rmc crate? We should give it a thought on how other safe non-deterministic constructions will look like so they follow a similar pattern.

**Comment by zhassan-aws** [comment]
> Can you expand the name a little bit? `NonDetSlice` for example.

Sure.

> Are you adding this to the rmc crate? We should give it a thought on how other safe non-deterministic constructions will look like so they follow a similar pattern.

Yes, that's what I intend to do.

**Comment by camshaft** [comment]
You should implement https://doc.rust-lang.org/std/ops/trait.Deref.html and https://doc.rust-lang.org/std/ops/trait.DerefMut.html for this type. Then you don't even need to call the conversion methods in most cases.

**Comment by zhassan-aws** [comment]
Thanks @camshaft! This is the updated API:
```rust
use std::ops::{Deref, DerefMut};

pub struct NonDetSlice<T, const MAX_SLICE_LENGTH: usize> {
    arr: [T; MAX_SLICE_LENGTH],
    slice_len: usize,
}

impl<T, const MAX_SLICE_LENGTH: usize> NonDetSlice<T, MAX_SLICE_LENGTH> {
    pub fn new() -> Self {
        let arr: [T; MAX_SLICE_LENGTH] = rmc::nondet();
        let slice_len: usize = rmc::nondet();
        rmc::assume(slice_len <= MAX_SLICE_LENGTH);
        Self { arr, slice_len }
    }

    pub fn get_slice(&self) -> &[T] {
        &self.arr[..self.slice_len]
    }

    pub fn get_slice_mut(&mut self) -> &mut [T] {
        &mut self.arr[..self.slice_len]
    }
}

impl<T, const MAX_SLICE_LENGTH: usize> Deref for NonDetSlice<T, MAX_SLICE_LENGTH> {
    type Target = [T];

    fn deref(&self) -> &Self::Target {
        self.get_slice()
    }
}

impl<T, const MAX_SLICE_LENGTH: usize> DerefMut for NonDetSlice<T, MAX_SLICE_LENGTH> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        self.get_slice_mut()
    }
}
```
and how it can be used:
```rust
fn main() {
    let mut nds: NonDetSlice<u8, 10> = NonDetSlice::new();
    let s: &mut [u8] = &mut nds; // <---- relies on Deref coercion
    assert!(s.len() <= 10);
    if s.len() > 0 {
        s[0] = 5;
    }
    assert!(s.len() == 0 || s[0] == 5);
}
```

**Comment by camshaft** [comment]
Nice thing is you don't even need to borrow it. You can just refer to slice methods as though they were on the NonDetSlice: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=753a3843737acdda6d8d228750e65888

**Comment by zhassan-aws** [comment]
Nice, thanks!
