### ISSUE TITLE
Remove dependency on `x.py`

### ISSUE THREAD

**Issue by avanhatt** [model-checking/rmc#641]
From deep dive: It would be nice to have a little `build-rmc` script that calls `x.py`, rebuilds the rmc lib, and build any new tangential executables.

**Comment by avanhatt** [comment]
This should also build the Rust executable for linking vtable restrictions:

```rust
# Build tool for linking RMC pointer restrictions
cargo build --release --manifest-path src/tools/rmc-link-restrictions/Cargo.toml 
```

**Comment by avanhatt** [comment]
DSN thought: we also might want to move spare executable/tools like this outside of `src/tools` and into their own separate folder in the RMC repo.

**Comment by tautschnig** [comment]
Apart from the fact that I'd +1 this request: having figured out that I need to build the library, doing so fails for me with:
```
$ scripts/setup/build_rmc_lib.sh
error: failed to load manifest for workspace member `/home/ub-backup/tautschn/rmc.git/src/bootstrap`

Caused by:
  failed to parse manifest at `/home/ub-backup/tautschn/rmc.git/src/bootstrap/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
```
on both Ubuntu 18.04 and 20.04. Based on https://github.com/rust-analyzer/rust-analyzer/issues/10742 my guess is that `rustc` on these platforms (1.53.0 on both of them) is too old. Is there some way to work around this? Ubuntu has 1.56 in the latest development version only, not in any release (https://launchpad.net/ubuntu/+source/rustc).

**Comment by zhassan-aws** [comment]
Can you try doing `rustup update`?

**Comment by tautschnig** [comment]
How do I (correctly) install `rustup` in the first place? It seems I can do `sudo snap install rustup --classic` (scary), and it will then install variants of various rust components that I already have installed via `apt`. I'm not quite sure what sort of state this is going to leave my system in. Is that the preferred (tried?) route to take?

**Comment by zhassan-aws** [comment]
The recommendation for Ubuntu 20.04 is to run the `./scripts/setup/install_rustup.sh` script. See the [Installation Guide](https://model-checking.github.io/rmc/install-guide.html) for more details.

**Comment by tautschnig** [comment]
Fair enough, which works modulo an extra `source $HOME/.cargo/env` (or starting a fresh shell).

**Comment by celinval** [comment]
We shall remove any usage of `x.py` and use `cargo build` directly since we no longer depend on the bootstrap script.
