### ISSUE TITLE
Book runner is broken

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/rmc#748]
Book runner results show 0 examples pass and the rest fail. Looks like this has been happening since #722.

**Comment by adpaco-aws** [comment]
Ran it locally and found several issues:
 1. It is forcing a build of the compiler (this is why it takes so long in CI).
 2. All examples are trivially failing.

The report shows all examples failed the `CHECK` step with:
```
ERROR: Could not find RMC binary.
Looked for: '/home/ubuntu/rmc-dash/target/*/rmc-compiler'
Was RMC successfully built first?
```

Not hard to fix, but it is probably better to move it out of `x.py` since we had to do it anyway.

**Comment by celinval** [comment]
We should also figure out a good strategy to fail the regression based on the book runner result.
